// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4q0ZHrYo6lwBs0OOH1t_ZGADSotJfjIM',
    appId: '1:428070319156:web:8ebacaff969ae4a3d24661',
    messagingSenderId: '428070319156',
    projectId: 'stridesync-2ded9',
    authDomain: 'stridesync-2ded9.firebaseapp.com',
    storageBucket: 'stridesync-2ded9.appspot.com',
    measurementId: 'G-YQE3P87CKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkmEHOpUbz2nr4mzb4OAIPP1fyVr-TDZE',
    appId: '1:428070319156:android:8645b15d82ada7c2d24661',
    messagingSenderId: '428070319156',
    projectId: 'stridesync-2ded9',
    storageBucket: 'stridesync-2ded9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOIJoZ0AugCkhIHoPSkumcRU5INGkZd9o',
    appId: '1:428070319156:ios:a1be44ef144add28d24661',
    messagingSenderId: '428070319156',
    projectId: 'stridesync-2ded9',
    storageBucket: 'stridesync-2ded9.appspot.com',
    iosBundleId: 'com.example.stridesyncUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOIJoZ0AugCkhIHoPSkumcRU5INGkZd9o',
    appId: '1:428070319156:ios:e4ee759df9c9fed1d24661',
    messagingSenderId: '428070319156',
    projectId: 'stridesync-2ded9',
    storageBucket: 'stridesync-2ded9.appspot.com',
    iosBundleId: 'com.example.stridesyncUi.RunnerTests',
  );
}
